import { generateToken, hashToken, hashPassword, verifyPassword, secureCompare } from './crypto';
import { ARGON2_CONFIG, SESSION, OAUTH, GOOGLE_OAUTH, GITHUB_OAUTH } from './constants';
import { Environment, Provider, OpenApiTag } from './enums';
import { cookieOptions, cookieSchema } from './cookie';
import {
    handleError,
    ELYSIA_ERRORS,
    ERROR_CLASSES,
    ParseError,
    BadRequestError,
    InvalidCookieSignatureError,
    UnauthorizedError,
    PaymentRequiredError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    GoneError,
    UnsupportedMediaTypeError,
    InvalidFileError,
    ValidationError,
    TooManyRequestsError,
    InternalServerError,
    UnknownError,
    ServiceUnavailableError,
} from './errors';
import {
    userSelectSchema,
    userInsertSchema,
    userUpdateSchema,
    accountSelectSchema,
    accountInsertSchema,
    accountUpdateSchema,
    sessionSelectSchema,
    sessionInsertSchema,
    sessionUpdateSchema,
    ErrorSchema,
    MessageSchema,
    VoidSchema,
    RegisterSchema,
    LoginSchema,
    OAuthCallbackQuerySchema,
} from './schemas';

import type {
    User,
    CreateUser,
    UpdateUser,
    Account,
    CreateAccount,
    UpdateAccount,
    Session,
    CreateSession,
    UpdateSession,
    OAuthUserInfo,
    GoogleTokenResponse,
    GoogleUserInfo,
    GitHubTokenResponse,
    GitHubUserInfo,
    GitHubEmail,
    Datasource,
    Cookies,
    OAuthCallbackQuery,
} from './types';

export { generateToken, hashToken, hashPassword, verifyPassword, secureCompare };
export { ARGON2_CONFIG, SESSION, OAUTH, GOOGLE_OAUTH, GITHUB_OAUTH };
export { Environment, Provider, OpenApiTag };
export { cookieOptions, cookieSchema };
export { ELYSIA_ERRORS, ERROR_CLASSES };
export { handleError };
export {
    ParseError,
    BadRequestError,
    InvalidCookieSignatureError,
    UnauthorizedError,
    PaymentRequiredError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    GoneError,
    UnsupportedMediaTypeError,
    InvalidFileError,
    ValidationError,
    TooManyRequestsError,
    InternalServerError,
    UnknownError,
    ServiceUnavailableError,
};
export {
    userSelectSchema,
    userInsertSchema,
    userUpdateSchema,
    accountSelectSchema,
    accountInsertSchema,
    accountUpdateSchema,
    sessionSelectSchema,
    sessionInsertSchema,
    sessionUpdateSchema,
    ErrorSchema,
    MessageSchema,
    VoidSchema,
    RegisterSchema,
    LoginSchema,
    OAuthCallbackQuerySchema,
};
export type {
    User,
    CreateUser,
    UpdateUser,
    Account,
    CreateAccount,
    UpdateAccount,
    Session,
    CreateSession,
    UpdateSession,
    OAuthUserInfo,
    GoogleTokenResponse,
    GoogleUserInfo,
    GitHubTokenResponse,
    GitHubUserInfo,
    GitHubEmail,
    Datasource,
    Cookies,
    OAuthCallbackQuery,
};
